config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :articles
  # only: [:show, :index, :new, :create, :edit, :update]. esto lo usamos cuando solo queremos mostrar algunas rutas, como quedo, muestra todas las posibles operaciones del backend.
  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
  get 'search', to: 'articles#search'
  get 'search/categories', to: 'categories#search'
  get 'search/users', to: 'users#search'
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    has_many :article_categories
    has_many :categories, through: :article_categories
    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
   

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]
    before_action :require_user, except: [:show, :index, :search]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def show
    end
    def search
        if params[:search].blank?
            flash[:alert] = "Please enter a search first"
            redirect_to articles_path and return
        else
            @parameter = params[:search].downcase
            @results = Article.all.where("lower(title || description) LIKE :search", search: "%#{@parameter}%")
        end
    end
    def index
        @articles = Article.paginate(page: params[:page], per_page: 5)
    end
    def new
        @article = Article.new
    end
    def edit
    end
    def create
        @article = Article.new (article_params)
        @article.user = current_user
        if @article.save
            flash[:notice] = "Article was created succesfully." 
        # redirect_to article_path(@article)esta es una forma larga, como es muy comun, hay un atajo que se pone abajo.
        redirect_to @article
        else
            render 'new'
        end
    end
    def update
        if @article.update(article_params)
        flash[:notice] = "Article was updated successfully"
        redirect_to @article
        else
            render 'edit'
        end
    end
    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private
    def set_article
    @article = Article.find(params[:id])
    end
    def article_params
        params.require(:article).permit(:title, :description, category_ids: [])
    end
    def require_same_user
        if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own articles"
        redirect_to @article
        end
    end
end

app/views/articles/_article.html.erb
<div id="page-content">
  <h2 class="text-center mt-4">Listing all articles</h2>
  <div class="container">
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            by <%= link_to article.user.username, user_path(article.user), method: :get, class: "nav-link" %>
          </div>
          <% if article.categories.any? %>
          <div class="mt-2">
          <%= render article.categories %>
          </div> 
        <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
              <%= button_to "Edit", edit_article_path(article), class: "btn btn-outline-info", method: :get %>
              <%= button_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, onclick: "return confirm('Are you sure?')" %>
            <% end %>
            </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div> 

app/views/articles/_form.html.erb
<div class="container-fluid">
<% if @article.errors.any? %>
<h2> The following errors prevented the article from being saved </h2>
<ul>
<% @article.errors.full_messages.each do |message| %>
   <li> <%= message %> </li>
    <% end %>
    </ul>
<% end %>

<div class="row">
  <div class="col-xs-12">
    <%= form_for(@article, :html => { class: "form-horizontal", role: "form" }) do |f| %>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :title %>  
        </div>
        <div class="col-sm-8">
          <%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :description %>
        </div>
        <div class="col-sm-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Description of article" %>
        </div>
      </div>
      <div class="form-group">
      <%= f.label :category  %>
          
          </div>
          <div class="col-2 col-form-label text-light">
      <div class="container fluid">
      <div class="form-group row">
          
            <%= f.collection_select(:category_ids, Category.all, :id, :name,
            { prompt: "Make your selection from the list"}, { multiple: true, size: 5, class: "custom-select shadow rounded" }) %>
          </div>
        </div>
        </div>
        </div>
       
      <div class="form-group">
        <div class="col-sm-8 col-sm-offset-2">
          <%= f.submit class: "btn btn-primary btn-lg" %>
        </div>
      </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to "Cancel request and return to articles listing", articles_path %> ]      
    </div>
  </div>
</div>
</div>

app/views/articles/edit.html.erb
<h1>Edit an article</h1>

<%= render 'form' %>

 

app/views/articles/index.html.erb
<div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2 text-align:center" >
<h1 style="text-align: center">Articles listing page</h1>
<div class="row justify-content-md-center">
<div class="col-8 mt-4">
<%= form_tag search_path, method: :get do %>
   <div class="input-group">
     <%=text_field_tag :search, params[:search], placeholder: "Sort article by title or description", class: "form-control" %>
     <div class="input-goup-btn">
       <%=submit_tag "Search", class: "btn btn-info glyphicon glyphicon-search" %>
     </div>          
   </div>
   </div>
   </div>
 <% end %>

<% if logged_in? %>
<div class="text-center mt-4">
<%= button_to "Create an Article", new_article_path, method: :get, class: "btn btn-outline-info" %>
</div>
<% end %>
<div class="text-center mt-4">
<div class="flickr_pagination">
   <%= will_paginate @articles, :container => false %>
</div>
</div>
<%= render 'article' %>
<div class="flickr_pagination mb-4">
   <%= will_paginate @articles, :container => false %>
</div>
</div>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>
    

app/views/articles/search.html.erb
<div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2 text-align:center" >
<div id="page-content">
  <h2 class="text-center mt-4">Your Search results:</h2>
<% @results.each do |result| %>
    <div class="row justify-content-md-center">
    <div class="col-8 mt-4">
      <div class="card text-center shadow mb-5 bg-white rounded">
        <div class="card-header font-italic">
          by <%= link_to result.user.username, user_path(result.user), method: :get, class: "nav-link" %>
        </div>
        <% if result.categories.any? %>
        <div class="mt-2">
        <%= render result.categories %>
        </div> 
      <% end %>
        <div class="card-body">
          <h5 class="card-title"><%= link_to result.title, article_path(result), class: "text-success" %></h5>
          <p class="card-text"><%= truncate(result.description, length: 100) %></p>
          <%= link_to "View", article_path(result), class: "btn btn-outline-success" %>
          <% if logged_in? && (result.user == current_user || current_user.admin?) %>
            <%= button_to "Edit", edit_article_path(result), class: "btn btn-outline-info", method: :get %>
            <%= button_to "Delete", article_path(result), class: "btn btn-outline-danger", method: :delete, onclick: "return confirm('Are you sure?')" %>
          <% end %>
          </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(result.created_at) %> ago, 
          edited <%= time_ago_in_words(result.updated_at) %> ago</small>
        </div>
      </div>
      <%= link_to '[ Return to articles listing ]', articles_path, class: "text-info" %>
    </div>
  </div>
<% end %>  
</div>
</div>  
</div>  

app/views/articles/show.html.erb
<div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
<div class="text-center mt-4">
<div class="card-header font-italic">

          by <%= @article.user.username if @article.user %>
         
          <% if @article.categories.any? %>
            <div class="mt-2">
            <%= render @article.categories %>
            </div> 
          <% end %>
        </div>
        <div class="card-body">
          <div class="card-text text-left"><%= simple_format(@article.description) %></div>
          <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
          <%= button_to "Edit", edit_article_path(@article), method: :get, class: "btn btn-outline-info" %>
          <%= button_to "Delete", article_path(@article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          <% end %>
        </div>
        <div class="card-footer text-muted">
          <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
          edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
</div>