config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :articles
  # only: [:show, :index, :new, :create, :edit, :update]. esto lo usamos cuando solo queremos mostrar algunas rutas, como quedo, muestra todas las posibles operaciones del backend.
  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
  get 'search', to: 'articles#search'
  get 'search/categories', to: 'categories#search'
  get 'search/users', to: 'users#search'
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    has_many :articles, dependent: :destroy
    validates :username, presence: true, uniqueness: {case_sensitive: false} , length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: {case_sensitive: false}, length: {maximum: 105}, format: {with: VALID_EMAIL_REGEX} 
    has_secure_password

    def self.search(search)
        if search
           where(["username LIKE ?", "%#{search}%"])
        else
            all
        end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:edit, :update]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    def show
        @articles = @user.articles.paginate(page: params[:page], per_page: 5) 
    end

    def search
        if params[:search].blank?
            flash[:alert] = "Please enter a search first"
            redirect_to users_path and return
        else
            @parameter = params[:search].downcase
            @results = User.all.where("lower(username) LIKE :search", search: "%#{@parameter}%")
        end
    end

    def index
        @user = User.search(params[:search])
        @users = User.paginate(page: params[:page], per_page: 5) 
    end
    def new
        @user = User.new
    end
    def edit
   
    end
    def update
        if @user.update(user_params)
            flash[:notice] = "Your account information was successfully update"
            redirect_to @user
        else
            render 'edit'
        end
    end

    def create
        @user = User.new(user_params)
        if @user.save
           session[:user_id] = @user.id
           flash[:notice] = "Welcome to the Alpha Blog #{@user.username}, you've successfully sign in!"
           redirect_to articles_path
        else
            render 'new'     
        end
    end

    def destroy
        @user.destroy
        session[:user_id] = nil if @user == current_user
        flash[:notice] = "Account and all associated articles where successfully deleted"
        redirect_to articles_path
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_user
        @user = User.find(params[:id])
    end
    
    def require_same_user
        if current_user != @user && !current_user.admin?
            flash[:alert] = "You can only edit or delete your own account"
            redirect_to @user
        end
    end
end

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @user %>
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter your email address" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>
        <hr>
        <div class="form-group row justify-content-center">
          <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %>
        </hr>
        <%= link_to '[ Cancel and return to articles listing ]', articles_path, class: "text-info" %>
    </div>
   </div>
</div> 

app/views/users/edit.html.erb
<div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
<h1 class="text-center mt-4">Edit your profile</h1>
<%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
<h1 class="text-center mt-4">Alpha Bloggers</h1>
<div class="flickr_pagination">
   <%= will_paginate @users, :container => false %>
</div>
<div class="row justify-content-md-center">
<div class="col-8 mt-4">
<%= form_tag search_users_path, method: :get do %>
   <div class="input-group">
     <%=text_field_tag :search, params[:search], placeholder: "Sort AlphaBloggers by name", class: "form-control" %>
     <div class="input-goup-btn">
       <%=submit_tag "Search", class: "btn btn-info glyphicon glyphicon-search" %>
     </div>          
     <% end %>
   </div>
   </div>
   </div>
<div class="container">
  <% @users.each do |user| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div 
          class="card-header font-italic" style="text-decoration: none">
          <h5 class="card-title" >
          <%= link_to user.username, user_path(user), method: :get, class: "nav-link" %>
        </h5>
          </div>
          <div class="card-body">
            <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
            <%= link_to "View profile", user, class: "btn btn-outline-success" %>
            <% if logged_in? %>
            <% if user == current_user %>
            <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-info" %>
            <% end %>
            <% if current_user.admin? %>
            <%= button_to "Delete user", user_path(user), class: "btn btn-outline-danger", method: :delete, onclick: "return confirm('Are you sure? This will delete selected user's account and all related articles')" %>
            <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(user.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="flickr_pagination mb-4">
   <%= will_paginate @users, :container => false %>
</div>
</div>

app/views/users/new.html.erb
<div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
<h1 class="text-center mt-4">Sign up for Alpha Blog</h1>
<%= render 'form' %>
</div>

app/views/users/search.html.erb
<div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2 text-align:center" >
<div id="page-content">
  <h2 class="text-center mt-4">Your search results:</h2>
  <div class="container">
<%@results.each do |result| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div 
          class="card-header font-italic" style="text-decoration: none">
          <h5 class="card-title" >
          <%= link_to result.username, user_path(result), method: :get, class: "nav-link" %>
        </h5>
          </div>
          <div class="card-body">
            <p class="card-text"><%= pluralize(result.articles.count, "article") %></p>
            <%= link_to "View profile", result, class: "btn btn-outline-success" %>
            <% if logged_in? %>
            <% if result == current_user %>
            <%= link_to "Edit profile", edit_user_path(result), class: "btn btn-outline-info" %>
            <% end %>
            <% if current_user.admin? %>
            <%= button_to "Delete user", user_path(result), class: "btn btn-outline-danger", method: :delete, onclick: "return confirm('Are you sure? This will delete selected user's account and all related articles')" %>
            <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(result.created_at) %> ago</small>
          </div>
        </div>
        <%= link_to '[ Return to Bloggers listing ]', users_path, class: "text-info" %>
        </div>
    </div>
<% end %>  
</div>
</div>  
</div>  

app/views/users/show.html.erb
<div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
<h1 class="text-center mt-4"><%= @user.username %>'s profile</h1>
<div class="text-center mt-4">
<%= button_to "Create an Article", new_article_path,method: :get, class: "btn btn-outline-info" %>
<% if logged_in? && @user == current_user %>
<%= button_to "Edit your profile", edit_user_path(@user),method: :get, class: "btn btn-outline-info" %>
<%= button_to "Delete your profile", user_path(current_user), class: "btn btn-outline-danger", method: :delete, onclick: "return confirm('Are you sure? This will delete your account and all related articles')" %>
<% if current_user.admin? %>
<%= button_to "Create a Category", new_category_path, method: :get, class: "btn btn-outline-info" %>
<% end %>
<% end %>
</div>
<h3 class="text-center mt-4">Articles</h3>
<div class="flickr_pagination">
   <%= will_paginate @articles, :container => false %>
</div>
<%= render 'articles/article' %>
<div class="flickr_pagination mb-4">
   <%= will_paginate @articles, :container => false %>
</div>
</div>
</div>