config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :articles
  # only: [:show, :index, :new, :create, :edit, :update]. esto lo usamos cuando solo queremos mostrar algunas rutas, como quedo, muestra todas las posibles operaciones del backend.
  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
  get 'search', to: 'articles#search'
  get 'search/categories', to: 'categories#search'
  get 'search/users', to: 'users#search'
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
before_action :require_admin, except: [:index, :show, :search]
    def new
        @category = Category.new
    end
    def search
        if params[:search].blank?
            flash[:alert] = "Please enter a search first"
            redirect_to categories_path and return
        else
            @parameter = params[:search].downcase
            @results = Category.all.where("lower(name) LIKE :search", search: "%#{@parameter}%")
        end
    end
    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end
    def create
        @category = Category.new(category_params)
        if @category.save
        flash[:notice] = "Category was successfully created"
        redirect_to @category
        else
            render 'new'
        end
    end
    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 5) 
    end
    def edit
        @category = Category.find(params[:id])
    end
    def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
            flash[:notice] = "Category was successfully update"
            redirect_to @category
        else
            render 'edit'
        end
    end

    private
    def category_params
        params.require(:category).permit(:name)
    end
    def require_admin
       if  !(logged_in? && current_user.admin?)
        flash[:alert] = "Only admins can perform that action"
        redirect_to categories_path
        end
    end
end

app/views/categories/_category.html.erb
<%= button_to category.name, category_path(category), method: :get, class:"badge badge-pill badge-info mr-1" %>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, "Category name", class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Enter a name" %>
          </div>
        </div>
        <hr>
        <div class="form-group row justify-content-center">
          <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %>

app/views/categories/edit.html.erb
<div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
<h1 class="text-center mt-4">Edit a category</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'form' %>
        </hr>
        <%= link_to '[ Cancel and return to category ]', category_path(@category), class: "text-info" %>
    </div>
   </div>
</div> 
</div>

app/views/categories/index.html.erb
<div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2 text-align:center" >
<h1 class="text-center mt-4">Categories</h1>
<div class="flickr_pagination">
  <%= will_paginate @categories, :container => false %>
</div>
<div class="row justify-content-md-center">
<div class="col-8 mt-4">
<%= form_tag search_categories_path, method: :get do %>
   <div class="input-group">
     <%=text_field_tag :search, params[:search], placeholder: "Sort category by name", class: "form-control" %>
     <div class="input-goup-btn">
       <%=submit_tag "Search", class: "btn btn-info glyphicon glyphicon-search" %>
     </div>          
     <% end %>
   </div>
   </div>
   </div>
<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
            <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>
<div class="flickr_pagination mb-4">
  <%= will_paginate @categories, :container => false %>
</div>
</div>

app/views/categories/new.html.erb
<div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
<h1 class="text-center mt-4">Create a new category</h1>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'form' %>
        </hr>
        <%= link_to '[ Cancel and return to categories listing ]', categories_path, class: "text-info" %>
    </div>
   </div>
</div> 
</div>

app/views/categories/search.html.erb
<div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2 text-align:center" >
<div id="page-content">
  <h2 class="text-center mt-4">Your Search results:</h2>
  <div class="container">
<%@results.each do |result| %>
        <div class="row justify-content-md-center">
          <div class="col-4 mt-4">
            <div class="card text-center shadow mb-5 bg-white rounded">
              <div class="card-body">
                <h5 class="card-title"><%= link_to result.name, category_path(result), class: "text-success" %></h5>
                <p class="card-text"><%= pluralize(result.articles.count, "article") %></p>
              </div>
              <div class="card-footer text-muted">
                <small>Created <%= time_ago_in_words(result.created_at) %> ago, 
                edited <%= time_ago_in_words(result.updated_at) %> ago</small>
              </div>
            </div>
            <%= link_to '[ Return to categories listing ]', categories_path, class: "text-info" %>
          </div>
        </div>
<% end %>  
</div>
</div>  
</div>  

app/views/categories/show.html.erb
<div class="col-xs-12 col-sm-10 col-md-8 col-sm-offset-1 col-md-offset-2">
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
  <div class="text-center mt-4">
    <%= link_to "Edit category name", edit_category_path(@category), class: "btn btn-outline-info" %>
  </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination">
  <%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<div class="flickr_pagination mb-4">
  <%= will_paginate @articles, :container => false %>
</div> 


</div>