config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :articles
  # only: [:show, :index, :new, :create, :edit, :update]. esto lo usamos cuando solo queremos mostrar algunas rutas, como quedo, muestra todas las posibles operaciones del backend.
  get 'signup', to: 'users#new'
  # post 'users', to: 'users#create'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :categories, except: [:destroy]
  get 'search', to: 'articles#search'
  get 'search/categories', to: 'categories#search'
  get 'search/users', to: 'users#search'
end

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
  <div class="row">
    <nav class="navbar navbar-expand-lg navbar-light bg-light" >
    <div class="container-fluid">
      <a class="navbar-brand" href="#">ALPHA BLOG</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Home', root_path, method: :get, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Bloggers', users_path, method: :get, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Articles', articles_path, method: :get, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to 'Categories', categories_path, method: :get, class: "nav-link" %>
          </li>
          <% if logged_in? %>
          <li class="nav-item"> 
            <%= "(Admin)" if current_user.admin? %>
            <%= link_to current_user.username, user_path(current_user), class: 'nav-link', method: :get %>
          </li>
          <hr>
          <li class="nav-item">
            <%= button_to 'Logout', logout_path, class: 'btn btn-danger', method: :delete %>
          </li>
          <% else %>
          <li class="nav-item">
          <%= link_to 'Sign Up!', signup_path, method: :get, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to 'Log in', login_path, class: 'btn btn-success' %>
          </li>
          <% end %>
        </ul>
        </div>
        <div class="nav navbar-nav navbar-right">
       


      </div>        
    </nav>
    </div>
    <%= render 'layouts/messages' %>
      <%= yield %>
      </body>
      </div>
     
</html>